# 8 GPUs
### model
model_name_or_path: Qwen/Qwen3-VL-8B-Instruct
image_max_pixels: 589824
image_min_pixels: 1024
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: mfr_117k_p2

template: qwen3_vl # [qwen3_vl](by default it's with thinking) or [qwen3_vl_nothink] --> {./LLaMA-Factory/src/llamafactory/data/template.py line 1933}
packing: true
cutoff_len: 32768
max_samples: 10000000
# overwrite_cache: true
tokenized_path: tokenized_data/mfr_117k
hf_hub_token: ""  # set your HuggingFace token here

preprocessing_num_workers: 32 
dataloader_num_workers: 4 

### output
output_dir: checkpoints/mfr_8b
logging_steps: 10
save_steps: 10000000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 1800000000
resume_from_checkpoint: null
flash_attn: fa2
seed: 42
enable_liger_kernel: true
gradient_checkpointing: true
